name: CI

on:
  push:
    branches:
    - main
  pull_request:
    

jobs:

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Tests Python 3.12 - Ubuntu
          # Doctests are run only for most recent Python (see noxfile.py)
          os: ubuntu-latest
          python-version: '3.13'

        - name: Tests, Python 3.12 - MacOS
          os: macos-latest
          python-version: '3.12'
          
        - name: Python 3.12 - Windows
          os: windows-latest
          python-version: '3.12'


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: |
        pytest
